version: '2.2'

services:
    bareos_exporter:
        ports:
            - 9625
        build:
            context: ..
        command:
            - "-dsn"
            - "postgres://host=database user=postgres password=postgres dbname=postgres sslmode=disable"
            - "-job-discovery-days"
            - "20"
        depends_on:
            - database

    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./postgres:/docker-entrypoint-initdb.d/:ro

volumes:
    postgres:
