name: Run golint
on:
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: Jerome1337/golint-action@v1.0.2
      id: golint
      with:
        golint-path: './'
    - name: Comment gollint output to pull request
      uses: Beakyn/gha-comment-pull-request@v1.0.2
      if: always()
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        comment-message: |
          ### Golint Output
          Output:
          ```
          # test
          ${{steps.golint.outputs.golint-output}}
          ```
        delete-previous-comment: true

