name: Publish Docker image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: vierbergenlars/bareos_exporter
        username: vierbergenlars
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tag_names: true
